name: Cypress Test on CrowdDesk Product Configurator
on:
  workflow_dispatch:
jobs:
  check-product-configurator:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: cypress/integration/productConfigurator_spec.js
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
